services:
  app:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend:/frontend
    environment:
      - WATCHERPACK_POLLING=true
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
  
  nginx:
    container_name: server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app