services:
  app:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend:/frontend
    environment:
      - WATCHERPACK_POLLING=true
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  
  nginx:
    container_name: server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app